name: earth_kit
description: A new flutter plugin project.
version: 0.1.0
homepage: https://github.com/bnxm/earth_kit

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.1.0
  ffi: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.bendix.earth_kit
        pluginClass: EarthKitPlugin
      ios:
        pluginClass: EarthKitPlugin

  assets:
    - packages/earth_kit/data/countries_50m.json
    - packages/earth_kit/data/countries_110m.json
    - packages/earth_kit/data/land_110m.json
    - packages/earth_kit/data/land_50m.json
    - packages/earth_kit/data/rivers_50m.json
    - packages/earth_kit/data/rivers_110m.json
    - packages/earth_kit/data/lakes_50m.json
    - packages/earth_kit/data/lakes_110m.json

